//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/AR Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ARInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ARInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AR Input Actions"",
    ""maps"": [
        {
            ""name"": ""ARTouchActions"",
            ""id"": ""c4c4bdd0-c29c-4436-9f6e-14ca4ff0c09c"",
            ""actions"": [
                {
                    ""name"": ""PlaceObject"",
                    ""type"": ""Value"",
                    ""id"": ""ceaaf857-90ef-49d8-b401-ed2c877ad326"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cc1db7d6-b3c9-49f7-9df1-9112491bccf7"",
                    ""path"": ""<Touchscreen>/primaryTouch/startPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ARTouchActions
        m_ARTouchActions = asset.FindActionMap("ARTouchActions", throwIfNotFound: true);
        m_ARTouchActions_PlaceObject = m_ARTouchActions.FindAction("PlaceObject", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ARTouchActions
    private readonly InputActionMap m_ARTouchActions;
    private IARTouchActionsActions m_ARTouchActionsActionsCallbackInterface;
    private readonly InputAction m_ARTouchActions_PlaceObject;
    public struct ARTouchActionsActions
    {
        private @ARInputActions m_Wrapper;
        public ARTouchActionsActions(@ARInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaceObject => m_Wrapper.m_ARTouchActions_PlaceObject;
        public InputActionMap Get() { return m_Wrapper.m_ARTouchActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ARTouchActionsActions set) { return set.Get(); }
        public void SetCallbacks(IARTouchActionsActions instance)
        {
            if (m_Wrapper.m_ARTouchActionsActionsCallbackInterface != null)
            {
                @PlaceObject.started -= m_Wrapper.m_ARTouchActionsActionsCallbackInterface.OnPlaceObject;
                @PlaceObject.performed -= m_Wrapper.m_ARTouchActionsActionsCallbackInterface.OnPlaceObject;
                @PlaceObject.canceled -= m_Wrapper.m_ARTouchActionsActionsCallbackInterface.OnPlaceObject;
            }
            m_Wrapper.m_ARTouchActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlaceObject.started += instance.OnPlaceObject;
                @PlaceObject.performed += instance.OnPlaceObject;
                @PlaceObject.canceled += instance.OnPlaceObject;
            }
        }
    }
    public ARTouchActionsActions @ARTouchActions => new ARTouchActionsActions(this);
    public interface IARTouchActionsActions
    {
        void OnPlaceObject(InputAction.CallbackContext context);
    }
}
